BUILT_IN_CASES = [
    {
        "id": "angle-vs-pawn-bottom",
        "name": "仙人指路對卒底炮",
        "fen": "rnbakabnr/9/2c4c1/p1p1p1p1p/9/2P6/P3P1P1P/1C5C1/9/RNBAKA1BR w - - 0 1",
        "expectedName": "仙人指路對卒底炮",
        "memoryPreset": {"redChoicePath": ["angle_pawn"]},
        "notes": "卒底炮只由黑方觸發，且炮在已挺起的三七路兵底",
        "source": "built_in",
    },
    {
        "id": "central-cannon",
        "name": "中炮",
        "fen": "rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C2C4/9/RNBAKABNR w - - 0 1",
        "expectedName": "中炮",
        "memoryPreset": {},
        "notes": "FEN 直接見紅方中相位有炮",
        "source": "built_in",
    },
    {
        "id": "central-vs-screen",
        "name": "中炮對屏風馬",
        "fen": "r1bakab1r/9/1cn3nc1/p1p1p1p1p/9/9/P1P1P1P1P/1C2C1N2/9/RNBAKAB1R w - - 0 1",
        "expectedName": "中炮對屏風馬",
        "memoryPreset": {},
        "notes": "黑方雙正馬且中間無炮",
        "source": "built_in",
    },
    {
        "id": "elephant-vs-palcorner",
        "name": "飛相對仕角炮",
        "fen": "rnbakabnr/9/3c3c1/p1p1p1p1p/9/9/P1P1P1P1P/1C2B2C1/9/RNBAKA1NR w - - 0 1",
        "expectedName": "飛相對仕角炮",
        "memoryPreset": {
            "redChoicePath": ["fly_elephant"],
            "blackChoicePath": ["palcorner_cannon"],
            "blackWing": "right",
        },
        "notes": "仕角炮需用原炮橫移歷史確定方向",
        "source": "built_in",
    },
    {
        "id": "horse-vs-screen",
        "name": "起馬對屏風馬",
        "fen": "r1bakab1r/9/1cn3nc1/p1p1p1p1p/9/2P6/P3P1P1P/1C4NC1/9/RNBAKAB1R w - - 0 1",
        "expectedName": "起馬對屏風馬",
        "memoryPreset": {},
        "notes": "FEN 檢視模式按辨認優先序推斷紅方先選起馬",
        "source": "built_in",
    },
    {
        "id": "non-opposing-pawns",
        "name": "三路兵對三路卒",
        "fen": "rnbakabnr/9/1c5c1/2p1p3p/p5p2/P1P6/4P1P1P/1C5C1/9/RNBAKABNR w - - 4 3",
        "expectedName": "仙人指路對挺卒",
        "memoryPreset": {},
        "notes": "紅七路兵與黑七路卒，不是三七線對兵",
        "source": "built_in",
    },
    {
        "id": "opposing-pawns-left",
        "name": "對兵局：紅三黑七",
        "fen": "rnbakabnr/9/1c5c1/2p1p3p/p5p2/P5P2/2P1P3P/1C5C1/9/RNBAKABNR w - - 4 3",
        "expectedName": "對兵局",
        "memoryPreset": {},
        "notes": "紅三路兵與黑七路卒同在 g 路",
        "source": "built_in",
    },
    {
        "id": "opposing-pawns-right",
        "name": "對兵局：紅七黑三",
        "fen": "rnbakabnr/9/1c5c1/4p1p1p/p1p6/P1P6/4P1P1P/1C5C1/9/RNBAKABNR w - - 4 3",
        "expectedName": "對兵局",
        "memoryPreset": {},
        "notes": "紅七路兵與黑三路卒同在 c 路",
        "source": "built_in",
    },
    {
        "id": "opposite-side-cannons",
        "name": "列炮",
        "fen": "rnbakabnr/9/4c2c1/p1p1p1p1p/9/9/P1P1P1P1P/1C2C4/9/RNBAKABNR w - - 2 2",
        "expectedName": "列炮",
        "memoryPreset": {},
        "notes": "紅方中炮由 h 線移入、黑方由 b 線移入，另兩炮分留相反側；只看四炮位置",
        "source": "built_in",
    },
    {
        "id": "same-side-cannons",
        "name": "順炮",
        "fen": "rnbakabnr/9/1c2c4/p1p1p1p1p/9/9/P1P1P1P1P/1C2C4/9/RNBAKABNR w - - 2 2",
        "expectedName": "順炮",
        "memoryPreset": {},
        "notes": "雙方中炮均由 h 線炮移入，另兩炮同留在 b 線；只看四炮位置",
        "source": "built_in",
    },
]
